baseurl = "/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = false
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Tomasz Kubicki"
title = "TK"
disqusshortname = ""
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "TK's personal blog"
copyright = "Copyright © 2017 Tomasz Kubicki"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = ""
email = ""
linkedin = "tomasz-kubicki"
twitter = "terziefff"
facebook = ""
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#eff4f7"
code = "#111"
type = "#97d28b"
special = "#ffcb8d"
value = "#3d83a5"
statement = "#ff8e91"
